### ISSUE TITLE
Epic: Create class Csvw::TableGroup with load from json method

### ISSUE THREAD

**Issue by josepajay** [GSS-Cogs/csv-validation#18]
Entire schema parsing and validation logic goes here. https://github.com/Data-Liberation-Front/csvlint.rb/blob/dd25a28626c7c84bc3ee8fbf23ce95b9d82a8769/lib/csvlint/csvw/table_group.rb#L56

- [x] Property checking logic #21 
- [x] Create Table object from json #24 
- [x] Essential functions from class Column #25 
- [x] Implement tableGroup class with load from json function #38
