### ISSUE TITLE
Epic: Create PropertyChecker to be used in TableGroup schema load & validate

### ISSUE THREAD

**Issue by josepajay** [GSS-Cogs/csv-validation#21]
Define Properties, Namespaces etc and the function to check if a property is valid. Return if the property is invalid or valid with warnings. 

Ruby implementation of the same:
https://github.com/Data-Liberation-Front/csvlint.rb/blob/dd25a28626c7c84bc3ee8fbf23ce95b9d82a8769/lib/csvlint/csvw/property_checker.rb#L3

- [x] DataType Property Checker #30 

- [x] Transformations Property Checker #31 

- [x] TableSchema Property Checker #32
- [x] ForeignKeys Property Checker #33
- [x] Reference Property Checker #34
- [x] Date format validation #29 
- [x] Number format validation #28 
- [x] Remaining property validation checks (smaller ones) #39
