### ISSUE TITLE
Epic: Schema parsing and validation

### ISSUE THREAD

**Issue by josepajay** [GSS-Cogs/csv-validation#6]
- Parse contents of file
- Ensure it complies with W3C CSV-W spec

- [x] #17 Learn csv-w schema structure 
- [x] #21 Create PropertyChecker to be used in TableGroup schema load & validate
- [x] #18 Create class Csvw::TableGroup with load from json method
- [x] #15 Create schema class with function to load from csvw-metadata 
- [ ] #47 Introduce dependency injection
- [x] #51 Ensure that schema file path can work as web urls or files

**Comment by josepajay** [comment]
Done the majority of this, still keeping the DI issue open.
